---
 - name: Download Composer
   delegate_to: localhost
   get_url: url="https://getcomposer.org/installer" dest="/tmp/composer_installer" mode="0755"
   
 - name: "Run Composer setup"
   delegate_to: localhost
   command: php "/tmp/composer_installer" --install-dir=/home/vagrant/ --filename=composer
   args:
     creates: "/home/vagrant/composer"
   
...