---
 - name: "Install apache server"
   apt: name={{item}} state=present
   become: yes
   with_items:
    - "apache2"
    - "libapache2-mod-php5"
    
 - name: "Disable default vhost"
   file: path="/etc/apache2/sites-enabled/000-default.conf" state=absent
   become: yes
...