---
 - name: "copy VHost config"
   become: yes
   template: src="../templates/site.conf" dest="/etc/apache2/sites-available/{{virtual_host_name}}.conf"   
   notify:
    - restart_apache
   
 - name: "Enable VHost config"
   become: yes
   file: src="/etc/apache2/sites-available/{{virtual_host_name}}.conf" dest="/etc/apache2/sites-enabled/{{virtual_host_name}}.conf" state=link
   notify:
    - restart_apache
...