<?php

namespace AppBundle\Repository;

/**
 * PollRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollRepository extends \Doctrine\ORM\EntityRepository
{
    public function findVotersCountById($poll)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        
        $qb->select($qb->expr()->count('p.id'))
           ->from('AppBundle:participant', 'p')
           ->where('p.poll = :poll')
           ->andWhere( $qb->expr()->isNotNull('p.chosenOption') )
           ->setParameter('poll', $poll);
           
        $query = $qb->getQuery();
                    
        try {
            return $query->getSingleScalarResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return -1;
        }
    }

}
